<?php

Git::$repositories['Gatekeeper'] = [
    'remote' => 'git@github.com:JarvusInnovations/Gatekeeper.git',
    'originBranch' => 'master',
    'workingBranch' => 'instances/' . Site::getConfig('primary_hostname'),
    'localOnly' => true,
    'trees' => [
        'dwoo-plugins',
        'event-handlers',
        'html-templates',
        'php-classes',
        'php-config' => [
            'exclude' => '#^/Git\\.config\\.php$#' // don't sync this file
        ],
        'php-migrations',
        'phpunit-tests',
        'sencha-workspace/pages',
        'site-root' => [
            'exclude' => [
                '#^/css(/|$)#', // don't sync /css, this directory is generated by /sass/compile
                '#^/js/pages(/|$)#' // don't sync /js/pages, this directory is generated by /sencha-cmd/pages-build
            ]
        ]
    ]
];

Git::$repositories['symfony-yaml'] = [
    'remote' => 'https://github.com/symfony/Yaml.git',
    'originBranch' => 'master',
    'workingBranch' => 'master',
    'trees' => [
        'php-classes/Symfony/Component/Yaml' => [
            'path' => '.',
            'exclude' => [
                '#\\.gitignore$#',
                '#^/Tests#',
                '#\\.md$#',
                '#composer\\.json#',
                '#phpunit\\.xml\\.dist#'
            ]
        ]
    ]
];

Git::$repositories['jarvus-highlighter'] = [
    'remote' => "https://github.com/JarvusInnovations/jarvus-highlighter.git",
    'originBranch' => 'master',
    'workingBranch' => 'master',
    'trees' => [
        "sencha-workspace/packages/jarvus-highlighter" => '.'
    ]
];