version: '2'

services:
  db:
    image: core/mysql
    environment:
      HAB_MYSQL: |
        app_username = "gatekeeper"
        app_password = "gatekeeper"
        bind = "0.0.0.0"
    volumes:
      - mysql-data:/hab/svc/mysql/data

  app:
    depends_on:
      - db
    extends:
      file: common-services.yml
      service: app

  http:
    depends_on:
      - app
    extends:
      file: common-services.yml
      service: http


volumes:
  mysql-data:
