# Default values for deployment
replicaCount: 1

hab:
  runtime:
    env_name: HAB_GATEKEEPER
    error:
      display: false
  composite:
    env_name: HAB_GATEKEEPER_COMPOSITE
    mysql:
      pkg_ident: 'core/mysql'

# these can be made up
  mysql:
    app_username: admin
    app_password: xTw9wYFe70
    bind: '0.0.0.0'

cert_manager:
  annotations:
    cluster_issuer: letsencrypt-prod
