#!/bin/bash

mkdir -p "{{pkg.svc_var_path}}/logs"
chown -R hab:hab "{{pkg.svc_var_path}}/logs"

{{#if cfg.site.holo.repo}}
    mkdir -p "{{pkg.svc_var_path}}/site"
    chown -R hab:hab "{{pkg.svc_var_path}}/site"
{{/if}}
